// backend/seedPermanentTools.js
// Standalone seed script for the PermanentTool collection.
//
// Usage:
//   node seedPermanentTools.js
//
// This script is idempotent — safe to run multiple times.
// It uses upsert logic so duplicates are never created.
// Tools are matched by name (case-insensitive) and website URL.

import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { upsertPermanentTool } from './src/services/permanentToolService.js';

dotenv.config();

// ── Seed Data: 40 Popular AI Tools ────────────────────────────────────────────
const SEED_TOOLS = [
  {
    name: 'ChatGPT',
    description: 'Conversational AI assistant by OpenAI. Understands and generates human-like text for a vast range of tasks including coding, writing, analysis, and more.',
    short_description: "OpenAI's leading conversational AI assistant.",
    category: 'Chat AI',
    website_url: 'https://chat.openai.com',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/240px-ChatGPT_logo.svg.png',
    pricing: 'Freemium',
    features: ['Conversational AI', 'Code generation', 'Summarization', 'Translation', 'Image analysis'],
    tags: ['openai', 'gpt', 'chatbot', 'llm', 'ai-assistant'],
    platform: ['Web', 'iOS', 'Android', 'API'],
    popularity_score: 100,
    rating: 4.8,
    use_cases: ['Customer support', 'Content creation', 'Code assistance', 'Research', 'Learning'],
    alternatives: ['Claude', 'Gemini', 'Copilot'],
  },
  {
    name: 'Claude',
    description: 'AI assistant by Anthropic, designed to be safe, helpful, and honest. Excels at long documents, complex reasoning, coding, and nuanced analysis.',
    short_description: "Anthropic's safe and helpful AI assistant.",
    category: 'Chat AI',
    website_url: 'https://claude.ai',
    pricing: 'Freemium',
    features: ['Long context window (200K tokens)', 'Document analysis', 'Code generation', 'Creative writing', 'Artifacts'],
    tags: ['anthropic', 'llm', 'chatbot', 'ai-assistant', 'safety'],
    platform: ['Web', 'API'],
    popularity_score: 95,
    rating: 4.7,
    use_cases: ['Document analysis', 'Creative writing', 'Code review', 'Research', 'Data extraction'],
    alternatives: ['ChatGPT', 'Gemini', 'Copilot'],
  },
  {
    name: 'Gemini',
    description: "Google's multimodal AI model capable of processing text, images, audio, and code. Available via Google products and as an API.",
    short_description: "Google's powerful multimodal AI model.",
    category: 'Chat AI',
    website_url: 'https://gemini.google.com',
    pricing: 'Freemium',
    features: ['Multimodal input', 'Code generation', 'Image understanding', 'Real-time search', 'Google Workspace integration'],
    tags: ['google', 'gemini', 'llm', 'multimodal'],
    platform: ['Web', 'iOS', 'Android', 'API'],
    popularity_score: 90,
    rating: 4.6,
    use_cases: ['Research', 'Coding', 'Image analysis', 'Writing', 'Data analysis'],
    alternatives: ['ChatGPT', 'Claude', 'Copilot'],
  },
  {
    name: 'Midjourney',
    description: 'Industry-leading AI image generation tool that creates stunning, photorealistic and artistic images from text prompts via Discord or web.',
    short_description: 'Industry-leading AI image generation.',
    category: 'Image Generation',
    website_url: 'https://www.midjourney.com',
    pricing: 'Paid',
    features: ['Text to image', 'High-resolution output', 'Style customization', 'Upscaling', 'Variation generation'],
    tags: ['image-generation', 'art', 'design', 'creative'],
    platform: ['Web', 'Discord'],
    popularity_score: 92,
    rating: 4.8,
    use_cases: ['Digital art', 'Concept art', 'Marketing visuals', 'Social media content'],
    alternatives: ['DALL-E 3', 'Stable Diffusion', 'Adobe Firefly'],
  },
  {
    name: 'DALL-E 3',
    description: "OpenAI's latest image generation model with dramatically improved instruction following and photorealistic quality, integrated into ChatGPT.",
    short_description: "OpenAI's advanced text-to-image generation model.",
    category: 'Image Generation',
    website_url: 'https://openai.com/dall-e-3',
    pricing: 'Paid',
    features: ['Text to image', 'Photorealistic images', 'High instruction fidelity', 'API access', 'ChatGPT integration'],
    tags: ['openai', 'image-generation', 'dall-e', 'ai-art'],
    platform: ['Web', 'API'],
    popularity_score: 85,
    rating: 4.6,
    use_cases: ['Marketing visuals', 'Product mockups', 'Illustration', 'Creative projects'],
    alternatives: ['Midjourney', 'Stable Diffusion', 'Adobe Firefly'],
  },
  {
    name: 'Stable Diffusion',
    description: 'Open-source AI image generation model by Stability AI. Can be run locally or via cloud APIs. Highly customizable through fine-tuning and LoRAs.',
    short_description: 'Open-source AI image generation model.',
    category: 'Image Generation',
    website_url: 'https://stability.ai',
    pricing: 'Open Source',
    features: ['Open source', 'Local deployment', 'Image generation', 'Fine-tuning', 'LoRA support', 'ComfyUI/A1111'],
    tags: ['stable-diffusion', 'open-source', 'image-generation', 'local-ai'],
    platform: ['Desktop', 'API', 'Web'],
    popularity_score: 82,
    rating: 4.4,
    use_cases: ['Local AI art', 'Custom model training', 'Batch generation', 'Research'],
    alternatives: ['Midjourney', 'DALL-E 3'],
  },
  {
    name: 'GitHub Copilot',
    description: 'AI-powered code completion and pair programmer by GitHub and OpenAI. Supports dozens of programming languages and integrates into popular IDEs.',
    short_description: 'AI pair programmer integrated into your IDE.',
    category: 'Coding',
    website_url: 'https://github.com/features/copilot',
    pricing: 'Paid',
    features: ['Code completion', 'Code generation', 'Multi-language support', 'IDE integration', 'Pull request summaries', 'Chat interface'],
    tags: ['coding', 'github', 'code-completion', 'developer-tools'],
    platform: ['Desktop', 'Web', 'VS Code', 'JetBrains'],
    popularity_score: 93,
    rating: 4.7,
    use_cases: ['Code completion', 'Bug fixing', 'Code explanation', 'Test generation'],
    alternatives: ['Cursor', 'Codeium', 'Tabnine'],
  },
  {
    name: 'Cursor',
    description: 'AI-native code editor built on VS Code with deep AI integration for code generation, refactoring, codebase chat, and multi-file edits.',
    short_description: 'The AI-first code editor for productive development.',
    category: 'Coding',
    website_url: 'https://cursor.sh',
    pricing: 'Freemium',
    features: ['AI code generation', 'Codebase chat', 'Refactoring', 'Multi-file edits', 'Tab completion', 'Agent mode'],
    tags: ['coding', 'code-editor', 'ai-coding', 'developer-tools'],
    platform: ['Desktop'],
    popularity_score: 88,
    rating: 4.8,
    use_cases: ['Full-stack development', 'Code refactoring', 'Debugging', 'Learning new codebases'],
    alternatives: ['GitHub Copilot', 'Windsurf', 'Codeium'],
  },
  {
    name: 'Copilot (Microsoft)',
    description: "Microsoft's AI assistant powered by GPT-4, integrated across Microsoft 365 apps, Windows, and Bing for productivity and research.",
    short_description: "Microsoft's AI assistant across all their products.",
    category: 'Productivity',
    website_url: 'https://copilot.microsoft.com',
    pricing: 'Freemium',
    features: ['Document creation', 'Email drafting', 'Spreadsheet analysis', 'Presentation generation', 'Web search'],
    tags: ['microsoft', 'productivity', 'office', 'llm'],
    platform: ['Web', 'Desktop', 'Windows'],
    popularity_score: 87,
    rating: 4.5,
    use_cases: ['Office productivity', 'Email management', 'Data analysis', 'Presentation creation'],
    alternatives: ['ChatGPT', 'Claude', 'Gemini'],
  },
  {
    name: 'Notion AI',
    description: 'AI writing and productivity assistant built directly into Notion workspace. Helps draft content, summarize notes, extract action items, and answer questions.',
    short_description: 'AI writing assistant built into Notion.',
    category: 'Productivity',
    website_url: 'https://notion.so/product/ai',
    pricing: 'Paid',
    features: ['Writing assistance', 'Summarization', 'Action items extraction', 'Q&A on documents', 'Auto-fill databases'],
    tags: ['notion', 'productivity', 'writing', 'notes', 'workspace'],
    platform: ['Web', 'iOS', 'Android', 'Desktop'],
    popularity_score: 80,
    rating: 4.5,
    use_cases: ['Note-taking', 'Project documentation', 'Meeting notes', 'Knowledge base management'],
    alternatives: ['Obsidian', 'Coda', 'Confluence AI'],
  },
  {
    name: 'Grammarly',
    description: 'AI writing assistant that checks grammar, spelling, tone, clarity, and style across any web application through a browser extension or desktop app.',
    short_description: 'AI-powered grammar and writing assistant.',
    category: 'Writing',
    website_url: 'https://www.grammarly.com',
    pricing: 'Freemium',
    features: ['Grammar checking', 'Tone detection', 'Plagiarism check', 'Style suggestions', 'GrammarlyGO generative AI'],
    tags: ['writing', 'grammar', 'editing', 'productivity'],
    platform: ['Web', 'Desktop', 'iOS', 'Android', 'Browser Extension'],
    popularity_score: 88,
    rating: 4.6,
    use_cases: ['Email writing', 'Essay editing', 'Business communication', 'Academic writing'],
    alternatives: ['Hemingway Editor', 'ProWritingAid', 'Quillbot'],
  },
  {
    name: 'Jasper',
    description: 'AI content creation platform designed for marketing teams. Generates blog posts, ad copy, emails, and social media content with brand voice customization.',
    short_description: 'AI writing platform for marketing and content teams.',
    category: 'Writing',
    website_url: 'https://www.jasper.ai',
    pricing: 'Paid',
    features: ['Blog writing', 'Ad copy', 'Email marketing', 'Brand voice', 'SEO integration', 'Multi-language'],
    tags: ['writing', 'marketing', 'content-creation', 'copywriting'],
    platform: ['Web'],
    popularity_score: 78,
    rating: 4.4,
    use_cases: ['Blog content', 'Social media copy', 'Ad campaigns', 'Email newsletters'],
    alternatives: ['Copy.ai', 'Writesonic', 'ChatGPT'],
  },
  {
    name: 'Copy.ai',
    description: 'AI-powered copywriting tool that generates marketing copy, emails, product descriptions, and blog content with customizable tones.',
    short_description: 'AI copywriting tool for marketing content.',
    category: 'Writing',
    website_url: 'https://www.copy.ai',
    pricing: 'Freemium',
    features: ['Ad copy', 'Email templates', 'Product descriptions', 'Social media posts', '90+ tools'],
    tags: ['writing', 'copywriting', 'marketing', 'ai-content'],
    platform: ['Web'],
    popularity_score: 75,
    rating: 4.3,
    use_cases: ['Marketing copy', 'Product descriptions', 'Email campaigns', 'Social media'],
    alternatives: ['Jasper', 'Writesonic', 'ChatGPT'],
  },
  {
    name: 'Runway',
    description: 'AI creative studio for video generation, editing, and visual effects. Used by professional filmmakers, content creators, and visual artists.',
    short_description: 'AI-powered video generation and editing platform.',
    category: 'Video AI',
    website_url: 'https://runwayml.com',
    pricing: 'Freemium',
    features: ['Video generation (Gen-2)', 'Green screen removal', 'Video editing', 'Motion tracking', 'Image animation'],
    tags: ['video', 'video-generation', 'creative', 'filmmaking', 'vfx'],
    platform: ['Web'],
    popularity_score: 82,
    rating: 4.5,
    use_cases: ['Film production', 'Social media videos', 'Visual effects', 'Content creation'],
    alternatives: ['Pika Labs', 'Sora', 'Synthesia'],
  },
  {
    name: 'Pika Labs',
    description: 'AI video generation platform that creates and edits high-quality videos from text descriptions and image inputs.',
    short_description: 'AI video generation from text and images.',
    category: 'Video AI',
    website_url: 'https://pika.art',
    pricing: 'Freemium',
    features: ['Text to video', 'Image to video', 'Video editing', 'Animation', 'Lip sync'],
    tags: ['video-generation', 'ai-video', 'text-to-video'],
    platform: ['Web'],
    popularity_score: 78,
    rating: 4.4,
    use_cases: ['Short video creation', 'Animation', 'Social media content', 'Marketing'],
    alternatives: ['Runway', 'Sora', 'Synthesia'],
  },
  {
    name: 'ElevenLabs',
    description: 'AI voice synthesis platform that creates ultra-realistic human voices for content creators, developers, and enterprises. Supports voice cloning.',
    short_description: 'Ultra-realistic AI voice synthesis and cloning.',
    category: 'Audio AI',
    website_url: 'https://elevenlabs.io',
    pricing: 'Freemium',
    features: ['Voice cloning', 'Text to speech', 'Multilingual support (29 languages)', 'API access', 'Real-time voice'],
    tags: ['audio', 'voice', 'tts', 'voice-cloning', 'speech'],
    platform: ['Web', 'API'],
    popularity_score: 85,
    rating: 4.7,
    use_cases: ['Podcast production', 'Audiobooks', 'Video narration', 'Customer service', 'Accessibility'],
    alternatives: ['Murf AI', 'Descript', 'Play.ht'],
  },
  {
    name: 'Murf AI',
    description: 'AI voiceover studio for creating professional-quality voiceovers for videos, podcasts, and presentations with 120+ realistic voices.',
    short_description: 'AI voiceover studio for professional content.',
    category: 'Audio AI',
    website_url: 'https://murf.ai',
    pricing: 'Freemium',
    features: ['Text to speech', 'Voice customization', 'Video voiceover', '120+ voices', 'Studio editor'],
    tags: ['audio', 'voiceover', 'tts', 'voice', 'studio'],
    platform: ['Web'],
    popularity_score: 72,
    rating: 4.4,
    use_cases: ['eLearning content', 'Marketing videos', 'Presentations', 'Podcasts'],
    alternatives: ['ElevenLabs', 'Descript', 'Play.ht'],
  },
  {
    name: 'Perplexity AI',
    description: 'AI-powered search engine that provides cited, accurate answers to questions using real-time web search and multiple AI models.',
    short_description: 'AI search engine with cited, real-time answers.',
    category: 'Research',
    website_url: 'https://www.perplexity.ai',
    pricing: 'Freemium',
    features: ['Real-time web search', 'Cited answers', 'Follow-up questions', 'File uploads', 'Multiple AI models'],
    tags: ['search', 'research', 'ai-search', 'citations', 'web-search'],
    platform: ['Web', 'iOS', 'Android', 'API'],
    popularity_score: 87,
    rating: 4.7,
    use_cases: ['Research', 'Fact-checking', 'Academic research', 'News monitoring', 'Competitive analysis'],
    alternatives: ['Google Bard', 'You.com', 'Bing Chat'],
  },
  {
    name: 'Elicit',
    description: 'AI research assistant that finds and summarizes academic papers, extracts key data, and synthesizes comprehensive literature reviews.',
    short_description: 'AI research assistant for academic literature.',
    category: 'Research',
    website_url: 'https://elicit.com',
    pricing: 'Freemium',
    features: ['Paper search', 'Literature review', 'Data extraction', 'Summarization', 'Hypothesis generation'],
    tags: ['research', 'academic', 'papers', 'literature-review', 'science'],
    platform: ['Web'],
    popularity_score: 70,
    rating: 4.5,
    use_cases: ['Academic research', 'Systematic reviews', 'Clinical research', 'Thesis writing'],
    alternatives: ['Consensus', 'Semantic Scholar', 'Research Rabbit'],
  },
  {
    name: 'Canva AI',
    description: 'Graphic design platform with integrated AI tools for image generation (Magic Media), background removal, design suggestions, and content creation.',
    short_description: 'AI-enhanced graphic design platform.',
    category: 'Design',
    website_url: 'https://www.canva.com',
    pricing: 'Freemium',
    features: ['AI image generation', 'Background removal', 'Design templates', 'Magic resize', 'Brand kit'],
    tags: ['design', 'graphic-design', 'image-editing', 'presentation', 'social-media'],
    platform: ['Web', 'iOS', 'Android', 'Desktop'],
    popularity_score: 90,
    rating: 4.7,
    use_cases: ['Social media graphics', 'Presentations', 'Marketing materials', 'Logo design', 'Video editing'],
    alternatives: ['Adobe Express', 'Figma', 'Adobe Firefly'],
  },
  {
    name: 'Adobe Firefly',
    description: "Adobe's family of creative AI generation tools including text-to-image, generative fill, text effects, and vector recoloring, integrated into Creative Cloud.",
    short_description: "Adobe's creative AI generation tools.",
    category: 'Design',
    website_url: 'https://firefly.adobe.com',
    pricing: 'Freemium',
    features: ['Text to image', 'Generative fill', 'Vector recoloring', 'Adobe CC integration', 'Text effects'],
    tags: ['design', 'adobe', 'image-generation', 'creative', 'photoshop'],
    platform: ['Web', 'Desktop'],
    popularity_score: 82,
    rating: 4.5,
    use_cases: ['Photo editing', 'Graphic design', 'Marketing visuals', 'Digital art', 'Illustration'],
    alternatives: ['Midjourney', 'DALL-E 3', 'Stable Diffusion'],
  },
  {
    name: 'n8n',
    description: 'Open-source, self-hostable workflow automation platform with 400+ integrations and native AI capabilities for building AI agents and automations.',
    short_description: 'Open-source workflow automation with AI features.',
    category: 'Automation',
    website_url: 'https://n8n.io',
    pricing: 'Open Source',
    features: ['Workflow automation', 'AI agent building', 'Self-hosting', '400+ integrations', 'Visual editor'],
    tags: ['automation', 'workflow', 'no-code', 'open-source', 'ai-agents'],
    platform: ['Web', 'Desktop', 'Self-hosted'],
    popularity_score: 78,
    rating: 4.6,
    use_cases: ['Business automation', 'Data pipelines', 'AI agents', 'API integration', 'Marketing automation'],
    alternatives: ['Zapier', 'Make', 'Activepieces'],
  },
  {
    name: 'Zapier',
    description: 'Workflow automation platform that connects 6,000+ apps including many AI tools to automate repetitive tasks without writing code.',
    short_description: 'Automation platform connecting thousands of apps.',
    category: 'Automation',
    website_url: 'https://zapier.com',
    pricing: 'Freemium',
    features: ['App integration (6000+)', 'Workflow automation', 'AI actions', 'Multi-step Zaps', 'Instant triggers'],
    tags: ['automation', 'workflow', 'no-code', 'integration', 'productivity'],
    platform: ['Web'],
    popularity_score: 85,
    rating: 4.5,
    use_cases: ['Business automation', 'Marketing workflows', 'CRM automation', 'E-commerce', 'Lead management'],
    alternatives: ['n8n', 'Make', 'Microsoft Power Automate'],
  },
  {
    name: 'Llama 3',
    description: "Meta's open-source large language model family. Available for local deployment, fine-tuning, and commercial use. Powers many open-source AI applications.",
    short_description: "Meta's powerful open-source LLM.",
    category: 'LLMs',
    website_url: 'https://llama.meta.com',
    pricing: 'Open Source',
    features: ['Open source', 'Local deployment', 'Fine-tuning', 'Commercial use', 'Multiple sizes (8B-405B)'],
    tags: ['llm', 'open-source', 'meta', 'local-ai', 'fine-tuning'],
    platform: ['API', 'Self-hosted'],
    popularity_score: 85,
    rating: 4.5,
    use_cases: ['Local AI applications', 'Custom AI products', 'Research', 'Fine-tuning experiments'],
    alternatives: ['Mistral', 'Gemma', 'Cohere'],
  },
  {
    name: 'Mistral',
    description: 'Efficient open-source language models by Mistral AI, known for strong performance relative to model size. Available via API and for local deployment.',
    short_description: 'Efficient open-source LLMs by Mistral AI.',
    category: 'LLMs',
    website_url: 'https://mistral.ai',
    pricing: 'Open Source',
    features: ['Open source', 'Efficient inference', 'API access', 'Fine-tuning', 'Multi-language support'],
    tags: ['llm', 'open-source', 'efficient', 'api', 'mistral'],
    platform: ['API', 'Self-hosted'],
    popularity_score: 78,
    rating: 4.4,
    use_cases: ['Cost-efficient AI', 'Local inference', 'API applications', 'Custom AI solutions'],
    alternatives: ['Llama 3', 'Cohere', 'Gemma'],
  },
  {
    name: 'Pinecone',
    description: 'Managed vector database for AI applications, enabling fast similarity search at massive scale for RAG pipelines, embeddings, and semantic search.',
    short_description: 'Managed vector database for AI and ML applications.',
    category: 'Data',
    website_url: 'https://www.pinecone.io',
    pricing: 'Freemium',
    features: ['Vector search', 'RAG support', 'Managed service', 'Scalable indexing', 'Hybrid search'],
    tags: ['vector-db', 'embeddings', 'rag', 'database', 'ai-infrastructure', 'semantic-search'],
    platform: ['API', 'Cloud'],
    popularity_score: 76,
    rating: 4.5,
    use_cases: ['RAG applications', 'Semantic search', 'Recommendation systems', 'Chatbot memory'],
    alternatives: ['Weaviate', 'Qdrant', 'Chroma'],
  },
  {
    name: 'Synthesia',
    description: 'AI video generation platform for creating professional training, marketing, and communication videos with realistic AI avatars in 130+ languages.',
    short_description: 'AI video generation with realistic avatars.',
    category: 'Video AI',
    website_url: 'https://www.synthesia.io',
    pricing: 'Paid',
    features: ['AI avatars (160+)', 'Text to video', '130+ languages', 'Custom avatars', 'Screen recording'],
    tags: ['video', 'avatars', 'training', 'corporate', 'e-learning'],
    platform: ['Web'],
    popularity_score: 78,
    rating: 4.5,
    use_cases: ['Corporate training', 'Product demos', 'Internal communications', 'eLearning'],
    alternatives: ['HeyGen', 'D-ID', 'Runway'],
  },
  {
    name: 'Descript',
    description: 'AI-powered audio and video editing tool with transcription, Overdub voice cloning, filler word removal, and collaborative editing capabilities.',
    short_description: 'AI audio and video editor with transcription.',
    category: 'Audio AI',
    website_url: 'https://www.descript.com',
    pricing: 'Freemium',
    features: ['Transcription', 'Audio editing', 'Video editing', 'Overdub voice cloning', 'Filler word removal', 'Collaboration'],
    tags: ['audio', 'video', 'transcription', 'editing', 'podcast'],
    platform: ['Desktop', 'Web'],
    popularity_score: 74,
    rating: 4.4,
    use_cases: ['Podcast editing', 'Video production', 'Interview editing', 'Content creation'],
    alternatives: ['ElevenLabs', 'Adobe Audition', 'Riverside'],
  },
  {
    name: 'Replit',
    description: 'Browser-based IDE with integrated AI coding tools (Replit AI) for building, testing, and deploying applications directly in the browser.',
    short_description: 'Browser-based IDE with integrated AI coding tools.',
    category: 'Coding',
    website_url: 'https://replit.com',
    pricing: 'Freemium',
    features: ['Online IDE', 'AI code generation', 'Instant deployment', 'Collaboration', '50+ languages'],
    tags: ['coding', 'ide', 'web-development', 'collaboration', 'cloud-ide'],
    platform: ['Web', 'iOS', 'Android'],
    popularity_score: 80,
    rating: 4.4,
    use_cases: ['Learning to code', 'Rapid prototyping', 'Team collaboration', 'Hackathons'],
    alternatives: ['Cursor', 'CodeSandbox', 'StackBlitz'],
  },
  {
    name: 'Vercel v0',
    description: "Generative UI tool by Vercel that creates production-ready React components and full UI designs from text prompts using shadcn/ui components.",
    short_description: 'AI-powered React UI generation by Vercel.',
    category: 'Coding',
    website_url: 'https://v0.dev',
    pricing: 'Freemium',
    features: ['UI generation', 'React components', 'shadcn/ui', 'Tailwind CSS', 'Copy-paste code', 'Preview'],
    tags: ['coding', 'ui', 'react', 'frontend', 'design', 'shadcn'],
    platform: ['Web'],
    popularity_score: 78,
    rating: 4.5,
    use_cases: ['UI prototyping', 'Component generation', 'Landing pages', 'Dashboard design'],
    alternatives: ['Cursor', 'Framer AI', 'Webflow AI'],
  },
  {
    name: 'HubSpot AI',
    description: "AI-powered features across HubSpot's CRM and marketing platform including AI content generation, email personalization, lead scoring, and chatbots.",
    short_description: "AI features in HubSpot's CRM and marketing platform.",
    category: 'Marketing',
    website_url: 'https://www.hubspot.com/artificial-intelligence',
    pricing: 'Freemium',
    features: ['AI content generation', 'Email personalization', 'Lead scoring', 'Chatbots', 'Predictive analytics'],
    tags: ['marketing', 'crm', 'automation', 'content', 'sales'],
    platform: ['Web', 'iOS', 'Android'],
    popularity_score: 80,
    rating: 4.4,
    use_cases: ['Lead generation', 'Email marketing', 'Customer segmentation', 'Sales forecasting'],
    alternatives: ['Salesforce Einstein', 'Marketo', 'ActiveCampaign'],
  },
  {
    name: 'Surfer SEO',
    description: 'AI-powered SEO content optimization platform that analyzes top-ranking pages to provide data-driven content recommendations for better rankings.',
    short_description: 'AI SEO optimization for content creation.',
    category: 'Marketing',
    website_url: 'https://surferseo.com',
    pricing: 'Paid',
    features: ['Content optimization', 'Keyword research', 'SERP analysis', 'AI writing', 'Content audit'],
    tags: ['seo', 'marketing', 'content', 'writing', 'rankings'],
    platform: ['Web', 'Browser Extension'],
    popularity_score: 75,
    rating: 4.5,
    use_cases: ['Blog SEO', 'Content strategy', 'Keyword optimization', 'Competitive analysis'],
    alternatives: ['Clearscope', 'MarketMuse', 'Semrush Writing Assistant'],
  },
  {
    name: 'Framer AI',
    description: 'AI-powered website builder that generates complete, responsive websites from text prompts with professional design and CMS capabilities.',
    short_description: 'AI website builder that generates sites from text.',
    category: 'Design',
    website_url: 'https://www.framer.com',
    pricing: 'Freemium',
    features: ['AI website generation', 'Responsive design', 'CMS integration', 'Component library', 'Custom code'],
    tags: ['design', 'website-builder', 'web-design', 'no-code', 'ai-generated'],
    platform: ['Web'],
    popularity_score: 75,
    rating: 4.5,
    use_cases: ['Portfolio sites', 'Marketing websites', 'SaaS landing pages', 'Design prototyping'],
    alternatives: ['Webflow', 'Wix AI', 'Squarespace AI'],
  },
  {
    name: 'Make',
    description: 'Visual workflow automation platform (formerly Integromat) for building complex automated workflows with AI capabilities and 1000+ app integrations.',
    short_description: 'Visual workflow automation for complex scenarios.',
    category: 'Automation',
    website_url: 'https://www.make.com',
    pricing: 'Freemium',
    features: ['Visual workflow builder', 'AI modules', 'Data transformation', '1000+ apps', 'Error handling'],
    tags: ['automation', 'workflow', 'integration', 'visual-builder', 'no-code'],
    platform: ['Web'],
    popularity_score: 77,
    rating: 4.4,
    use_cases: ['Complex automations', 'Data synchronization', 'E-commerce workflows', 'Marketing automation'],
    alternatives: ['Zapier', 'n8n', 'Workato'],
  },
  {
    name: 'Khanmigo',
    description: "Khan Academy's AI tutor powered by GPT-4, designed to help students learn through Socratic questioning, providing hints rather than direct answers.",
    short_description: 'AI tutor by Khan Academy for student learning.',
    category: 'Education',
    website_url: 'https://www.khanacademy.org/khan-labs',
    pricing: 'Freemium',
    features: ['Socratic tutoring', 'Homework help', 'Math solving', 'Writing feedback', 'Teacher tools'],
    tags: ['education', 'tutoring', 'students', 'learning', 'k-12'],
    platform: ['Web'],
    popularity_score: 72,
    rating: 4.5,
    use_cases: ['K-12 tutoring', 'Math help', 'Essay assistance', 'Test preparation'],
    alternatives: ['Duolingo', 'Coursera AI', 'Chegg AI'],
  },
  {
    name: 'Cohere',
    description: 'Enterprise AI platform providing language models, embeddings, reranking, and retrieval tools built for business applications and RAG pipelines.',
    short_description: 'Enterprise NLP and language model platform.',
    category: 'LLMs',
    website_url: 'https://cohere.com',
    pricing: 'Freemium',
    features: ['Text generation', 'Embeddings', 'Reranking', 'RAG support', 'Fine-tuning', 'On-prem deployment'],
    tags: ['llm', 'enterprise', 'embeddings', 'nlp', 'rag', 'api'],
    platform: ['API'],
    popularity_score: 72,
    rating: 4.3,
    use_cases: ['Enterprise AI', 'Semantic search', 'Document processing', 'Customer support AI'],
    alternatives: ['OpenAI API', 'Anthropic API', 'Google Vertex AI'],
  },
  {
    name: 'Sora',
    description: "OpenAI's revolutionary text-to-video AI model capable of generating realistic, high-quality videos up to a minute long from text descriptions.",
    short_description: "OpenAI's advanced text-to-video generation model.",
    category: 'Video AI',
    website_url: 'https://sora.com',
    pricing: 'Paid',
    features: ['Text to video', 'High-quality output', 'Long-form video (up to 60s)', 'Consistent characters', '1080p output'],
    tags: ['openai', 'video-generation', 'sora', 'ai-video', 'text-to-video'],
    platform: ['Web'],
    popularity_score: 85,
    rating: 4.6,
    use_cases: ['Film production', 'Marketing videos', 'Creative projects', 'Storyboarding'],
    alternatives: ['Runway', 'Pika Labs', 'Synthesia'],
  },
  {
    name: 'Udio',
    description: 'AI music generation platform that creates original, full songs with lyrics, vocals, and instrumentation from text prompts in any genre.',
    short_description: 'AI music generation from text prompts.',
    category: 'Audio AI',
    website_url: 'https://www.udio.com',
    pricing: 'Freemium',
    features: ['Music generation', 'Lyrics generation', 'Custom genres', 'Full song output', 'Remix capability'],
    tags: ['music', 'audio', 'music-generation', 'ai-music', 'creative'],
    platform: ['Web'],
    popularity_score: 74,
    rating: 4.3,
    use_cases: ['Background music', 'Jingles', 'Creative projects', 'Content creation', 'Prototyping music ideas'],
    alternatives: ['Suno AI', 'Mubert', 'Soundraw'],
  },
];

// ── Main Seed Function ─────────────────────────────────────────────────────────
async function run() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/airadar');
    console.log('✅ MongoDB connected for seeding PermanentTool collection...');
    console.log(`📦 Seeding ${SEED_TOOLS.length} AI tools...`);

    const results = { inserted: 0, updated: 0, skipped: 0, errors: [] };

    for (const toolData of SEED_TOOLS) {
      try {
        const { action, tool } = await upsertPermanentTool(toolData);
        results[action === 'inserted' ? 'inserted' : action === 'updated' ? 'updated' : 'skipped']++;
        const emoji = action === 'inserted' ? '✅' : action === 'updated' ? '🔄' : '⏭️';
        console.log(`  ${emoji} [${action.toUpperCase()}] ${tool.name}`);
      } catch (err) {
        results.errors.push({ name: toolData.name, error: err.message });
        console.error(`  ❌ [ERROR] ${toolData.name}: ${err.message}`);
      }
    }

    console.log('\n─────────────────────────────────────────────────────');
    console.log(`✅ Seed complete!`);
    console.log(`   Inserted : ${results.inserted}`);
    console.log(`   Updated  : ${results.updated}`);
    console.log(`   Skipped  : ${results.skipped}`);
    if (results.errors.length > 0) {
      console.log(`   Errors   : ${results.errors.length}`);
    }
    console.log('─────────────────────────────────────────────────────');

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error.message);
    process.exit(1);
  }
}

run();
