// backend/src/utils/seedGithubRepos.js
// Run: node src/utils/seedGithubRepos.js

import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config();

import GitHubRepository from '../models/GitHubRepository.js';

const repos = [
  {
    repository_name: 'ChatGPT',
    slug: 'chatgpt-openai',
    owner_name: 'openai',
    repository_url: 'https://github.com/openai/chatgpt-retrieval-plugin',
    description: 'The ChatGPT Retrieval Plugin lets you easily search and find personal or work documents by asking questions in natural language.',
    stars: 21000,
    forks: 3200,
    language: 'Python',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-11-01'),
    topics: ['chatgpt', 'openai', 'retrieval', 'plugin', 'nlp'],
    category: 'Chatbots',
    readme_summary: 'A retrieval plugin for ChatGPT that enables semantic search over documents using OpenAI embeddings.',
    installation_guide: 'pip install -r requirements.txt && uvicorn datastore.providers.redis_datastore:app',
    status: 'approved',
  },
  {
    repository_name: 'LangChain',
    slug: 'langchain',
    owner_name: 'langchain-ai',
    repository_url: 'https://github.com/langchain-ai/langchain',
    description: 'Build context-aware reasoning applications using LangChain — the framework for LLM-powered apps.',
    stars: 96000,
    forks: 15600,
    language: 'Python',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-12-01'),
    topics: ['llm', 'langchain', 'ai', 'agents', 'rag', 'openai'],
    category: 'LLMs',
    readme_summary: 'LangChain is a framework for building applications powered by large language models with chains, agents, and memory.',
    installation_guide: 'pip install langchain',
    status: 'approved',
  },
  {
    repository_name: 'Stable Diffusion WebUI',
    slug: 'stable-diffusion-webui',
    owner_name: 'AUTOMATIC1111',
    repository_url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
    description: 'A browser interface for Stable Diffusion, implemented using Gradio, supporting a wide range of features for image generation.',
    stars: 143000,
    forks: 27000,
    language: 'Python',
    license: 'AGPL-3.0',
    open_source: true,
    last_updated: new Date('2024-11-20'),
    topics: ['stable-diffusion', 'image-generation', 'gradio', 'ai-art', 'deep-learning'],
    category: 'Image Generation',
    readme_summary: 'Feature-rich web UI for Stable Diffusion image generation with support for txt2img, img2img, inpainting, and extensions.',
    installation_guide: 'git clone && python launch.py',
    status: 'approved',
  },
  {
    repository_name: 'Ollama',
    slug: 'ollama',
    owner_name: 'ollama',
    repository_url: 'https://github.com/ollama/ollama',
    description: 'Get up and running with large language models locally. Run Llama 3, Mistral, Gemma, and other models on your machine.',
    stars: 102000,
    forks: 8200,
    language: 'Go',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-12-05'),
    topics: ['llm', 'local-ai', 'llama', 'mistral', 'gemma', 'inference'],
    category: 'LLMs',
    readme_summary: 'Run large language models locally with a simple CLI. Supports Llama 3, Mistral, Phi-3, Gemma, and many more.',
    installation_guide: 'curl -fsSL https://ollama.com/install.sh | sh && ollama run llama3',
    status: 'approved',
  },
  {
    repository_name: 'AutoGPT',
    slug: 'autogpt',
    owner_name: 'Significant-Gravitas',
    repository_url: 'https://github.com/Significant-Gravitas/AutoGPT',
    description: 'AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools, so that you can focus on what matters.',
    stars: 170000,
    forks: 44800,
    language: 'Python',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-11-15'),
    topics: ['autogpt', 'autonomous-agents', 'openai', 'gpt-4', 'ai-agents'],
    category: 'Productivity',
    readme_summary: 'An experimental open-source application showcasing the capabilities of the GPT-4 language model for autonomous task completion.',
    installation_guide: 'git clone && pip install -r requirements.txt && python -m autogpt',
    status: 'approved',
  },
  {
    repository_name: 'Hugging Face Transformers',
    slug: 'huggingface-transformers',
    owner_name: 'huggingface',
    repository_url: 'https://github.com/huggingface/transformers',
    description: 'State-of-the-art Machine Learning for PyTorch, TensorFlow, and JAX — thousands of pretrained models for NLP, vision, audio, and more.',
    stars: 137000,
    forks: 27400,
    language: 'Python',
    license: 'Apache-2.0',
    open_source: true,
    last_updated: new Date('2024-12-03'),
    topics: ['transformers', 'nlp', 'bert', 'gpt', 'pytorch', 'tensorflow', 'machine-learning'],
    category: 'Research',
    readme_summary: 'Thousands of pretrained models for natural language processing, computer vision, audio, and multimodal tasks.',
    installation_guide: 'pip install transformers',
    status: 'approved',
  },
  {
    repository_name: 'Whisper',
    slug: 'whisper-openai',
    owner_name: 'openai',
    repository_url: 'https://github.com/openai/whisper',
    description: 'Robust Speech Recognition via Large-Scale Weak Supervision — a general-purpose speech recognition model by OpenAI.',
    stars: 75000,
    forks: 9000,
    language: 'Python',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-10-10'),
    topics: ['speech-recognition', 'asr', 'openai', 'audio', 'transcription', 'whisper'],
    category: 'Audio',
    readme_summary: 'OpenAI Whisper is an automatic speech recognition system trained on 680,000 hours of multilingual web audio.',
    installation_guide: 'pip install openai-whisper && whisper audio.mp3 --model medium',
    status: 'approved',
  },
  {
    repository_name: 'LlamaIndex',
    slug: 'llamaindex',
    owner_name: 'run-llama',
    repository_url: 'https://github.com/run-llama/llama_index',
    description: 'LlamaIndex is a data framework for your LLM application. Build RAG pipelines, agents, and workflows over your data.',
    stars: 38000,
    forks: 5400,
    language: 'Python',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-12-04'),
    topics: ['llm', 'rag', 'agents', 'llama-index', 'openai', 'vector-database'],
    category: 'Research',
    readme_summary: 'LlamaIndex provides data connectors, indexes, and query engines to build context-augmented LLM applications.',
    installation_guide: 'pip install llama-index',
    status: 'approved',
  },
  {
    repository_name: 'Midjourney Proxy',
    slug: 'midjourney-proxy',
    owner_name: 'novicezk',
    repository_url: 'https://github.com/novicezk/midjourney-proxy',
    description: 'A proxy for Midjourney API — supports image generation, upscale, variation, and batch generation via Discord.',
    stars: 9800,
    forks: 2200,
    language: 'Java',
    license: 'Apache-2.0',
    open_source: true,
    last_updated: new Date('2024-09-20'),
    topics: ['midjourney', 'image-generation', 'discord', 'api-proxy', 'ai-art'],
    category: 'Image Generation',
    readme_summary: 'Proxy service for Midjourney that allows programmatic access to image generation through the Discord API.',
    installation_guide: 'docker pull novicezk/midjourney-proxy:latest && docker run -d -p 8080:8080',
    status: 'approved',
  },
  {
    repository_name: 'CrewAI',
    slug: 'crewai',
    owner_name: 'crewAIInc',
    repository_url: 'https://github.com/crewAIInc/crewAI',
    description: 'Framework for orchestrating role-playing, autonomous AI agents. By fostering collaborative intelligence, CrewAI empowers agents to work together seamlessly.',
    stars: 26000,
    forks: 3600,
    language: 'Python',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-12-01'),
    topics: ['ai-agents', 'multi-agent', 'crewai', 'llm', 'automation', 'openai'],
    category: 'Productivity',
    readme_summary: 'CrewAI enables building multi-agent systems where autonomous AI agents collaborate to complete complex tasks.',
    installation_guide: 'pip install crewai && crewai create my-project',
    status: 'approved',
  },
  {
    repository_name: 'Open Interpreter',
    slug: 'open-interpreter',
    owner_name: 'OpenInterpreter',
    repository_url: 'https://github.com/OpenInterpreter/open-interpreter',
    description: 'A natural language interface for computers — lets LLMs run code on your machine to complete any task.',
    stars: 57000,
    forks: 5100,
    language: 'Python',
    license: 'AGPL-3.0',
    open_source: true,
    last_updated: new Date('2024-11-25'),
    topics: ['llm', 'code-interpreter', 'natural-language', 'openai', 'automation'],
    category: 'Coding',
    readme_summary: 'Open Interpreter lets LLMs run code locally, giving you a ChatGPT Code Interpreter experience without restrictions.',
    installation_guide: 'pip install open-interpreter && interpreter',
    status: 'approved',
  },
  {
    repository_name: 'Bark',
    slug: 'bark-suno',
    owner_name: 'suno-ai',
    repository_url: 'https://github.com/suno-ai/bark',
    description: 'Bark is a transformer-based text-to-audio model created by Suno. It can generate highly realistic, multilingual speech and sound effects.',
    stars: 36000,
    forks: 4300,
    language: 'Python',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-08-15'),
    topics: ['text-to-speech', 'audio', 'tts', 'generative-ai', 'bark', 'suno'],
    category: 'Audio',
    readme_summary: 'Bark generates realistic speech, music, and sound effects from text prompts using a GPT-style transformer model.',
    installation_guide: 'pip install git+https://github.com/suno-ai/bark.git',
    status: 'approved',
  },
  {
    repository_name: 'Vercel AI SDK',
    slug: 'vercel-ai-sdk',
    owner_name: 'vercel',
    repository_url: 'https://github.com/vercel/ai',
    description: 'The AI Toolkit for TypeScript — build AI-powered applications with React, Next.js, Vue, Nuxt, SvelteKit, and more.',
    stars: 12000,
    forks: 1800,
    language: 'TypeScript',
    license: 'Apache-2.0',
    open_source: true,
    last_updated: new Date('2024-12-05'),
    topics: ['ai', 'nextjs', 'react', 'typescript', 'streaming', 'llm', 'vercel'],
    category: 'Coding',
    readme_summary: 'Vercel AI SDK provides hooks and utilities for building streaming AI UIs with React, Next.js, and other frameworks.',
    installation_guide: 'npm install ai',
    status: 'approved',
  },
  {
    repository_name: 'PrivateGPT',
    slug: 'privategpt',
    owner_name: 'zylon-ai',
    repository_url: 'https://github.com/zylon-ai/private-gpt',
    description: 'Interact with your documents using the power of GPT, 100% privately, no data leaks. Works without an internet connection.',
    stars: 54000,
    forks: 7300,
    language: 'Python',
    license: 'Apache-2.0',
    open_source: true,
    last_updated: new Date('2024-11-10'),
    topics: ['private-gpt', 'local-llm', 'rag', 'privacy', 'document-chat', 'offline'],
    category: 'Research',
    readme_summary: 'PrivateGPT lets you chat with your documents completely offline using local LLMs, ensuring full data privacy.',
    installation_guide: 'pip install "private-gpt[ui,llms-ollama,embeddings-ollama,vector-stores-qdrant]"',
    status: 'approved',
  },
  {
    repository_name: 'MetaGPT',
    slug: 'metagpt',
    owner_name: 'geekan',
    repository_url: 'https://github.com/geekan/MetaGPT',
    description: 'The Multi-Agent Framework: First AI Software Company — assign one line requirement, output user stories, competitive analysis, architecture, and code.',
    stars: 46000,
    forks: 5500,
    language: 'Python',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-11-30'),
    topics: ['multi-agent', 'software-engineering', 'gpt-4', 'code-generation', 'metagpt'],
    category: 'Coding',
    readme_summary: 'MetaGPT takes a one-line requirement and outputs complete software artifacts including PRD, architecture, and code.',
    installation_guide: 'pip install metagpt && metagpt "Create a snake game"',
    status: 'approved',
  },
  {
    repository_name: 'ComfyUI',
    slug: 'comfyui',
    owner_name: 'comfyanonymous',
    repository_url: 'https://github.com/comfyanonymous/ComfyUI',
    description: 'The most powerful and modular diffusion model GUI and backend with a graph/node based interface.',
    stars: 64000,
    forks: 6900,
    language: 'Python',
    license: 'GPL-3.0',
    open_source: true,
    last_updated: new Date('2024-12-04'),
    topics: ['stable-diffusion', 'comfyui', 'image-generation', 'node-graph', 'flux'],
    category: 'Image Generation',
    readme_summary: 'ComfyUI is a modular node-based GUI for Stable Diffusion and Flux, allowing complex image generation pipelines.',
    installation_guide: 'git clone && pip install -r requirements.txt && python main.py',
    status: 'approved',
  },
  {
    repository_name: 'Flowise',
    slug: 'flowise',
    owner_name: 'FlowiseAI',
    repository_url: 'https://github.com/FlowiseAI/Flowise',
    description: 'Drag & drop UI to build your customized LLM orchestration flow using LangchainJS.',
    stars: 33000,
    forks: 17500,
    language: 'TypeScript',
    license: 'Apache-2.0',
    open_source: true,
    last_updated: new Date('2024-12-02'),
    topics: ['langchain', 'llm', 'no-code', 'chatbot', 'rag', 'flowise', 'drag-drop'],
    category: 'Chatbots',
    readme_summary: 'Flowise is a low-code tool for building customized LLM flows and AI agents using a visual drag-and-drop interface.',
    installation_guide: 'npx flowise start',
    status: 'approved',
  },
  {
    repository_name: 'Dify',
    slug: 'dify',
    owner_name: 'langgenius',
    repository_url: 'https://github.com/langgenius/dify',
    description: 'Dify is an open-source LLM app development platform. Its intuitive interface combines AI workflow, RAG pipeline, agent capabilities, and more.',
    stars: 57000,
    forks: 8400,
    language: 'TypeScript',
    license: 'Apache-2.0',
    open_source: true,
    last_updated: new Date('2024-12-05'),
    topics: ['llm', 'rag', 'agents', 'workflow', 'openai', 'dify', 'app-development'],
    category: 'Productivity',
    readme_summary: 'Dify combines LLM workflow, RAG, agents, and model management in one platform to build production-ready AI apps.',
    installation_guide: 'docker compose up -d',
    status: 'approved',
  },
  {
    repository_name: 'GPT4All',
    slug: 'gpt4all',
    owner_name: 'nomic-ai',
    repository_url: 'https://github.com/nomic-ai/gpt4all',
    description: 'GPT4All is a free-to-use, locally running, privacy-aware chatbot — no GPU required. Run any LLM on your own hardware.',
    stars: 71000,
    forks: 7700,
    language: 'C++',
    license: 'MIT',
    open_source: true,
    last_updated: new Date('2024-11-28'),
    topics: ['local-llm', 'gpt4all', 'privacy', 'chatbot', 'cpu-inference', 'offline'],
    category: 'Chatbots',
    readme_summary: 'GPT4All lets you run powerful LLMs locally on your CPU — no internet, no GPU, full privacy.',
    installation_guide: 'Download installer from https://gpt4all.io',
    status: 'approved',
  },
  {
    repository_name: 'n8n',
    slug: 'n8n',
    owner_name: 'n8n-io',
    repository_url: 'https://github.com/n8n-io/n8n',
    description: 'Fair-code workflow automation platform with native AI capabilities. Build AI workflows connecting 400+ services with a visual editor.',
    stars: 50000,
    forks: 13200,
    language: 'TypeScript',
    license: 'SEE LICENSE',
    open_source: true,
    last_updated: new Date('2024-12-05'),
    topics: ['automation', 'workflow', 'ai', 'no-code', 'self-hosted', 'n8n', 'integrations'],
    category: 'Productivity',
    readme_summary: 'n8n is a workflow automation tool with 400+ integrations and built-in AI nodes for building intelligent automation pipelines.',
    installation_guide: 'npx n8n',
    status: 'approved',
  },
];

(async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    let inserted = 0;
    let skipped = 0;

    for (const repo of repos) {
      const exists = await GitHubRepository.findOne({ slug: repo.slug });
      if (exists) {
        skipped++;
        continue;
      }
      await GitHubRepository.create(repo);
      inserted++;
      console.log(`  ✅ Inserted: ${repo.repository_name}`);
    }

    console.log(`\nDone — inserted: ${inserted}, skipped (already exist): ${skipped}`);
    process.exit(0);
  } catch (e) {
    console.error('Seed error:', e.message);
    process.exit(1);
  }
})();
